flags: {}
packages:
- '.'

extra-deps:
- roman-numerals-0.5.1.5

- git: git@github.com:konn/latex-crossref.git
  commit: 79c9ac25f2bb1bfcb40f261a0ea4ffaefd295067

- git: git@github.com:konn/sake.git
  commit: 168a687ba2b9b1d802d302cba137b81b7e8b780a


resolver: lts-10.5

extra-include-dirs:
- /usr/local/opt/icu4c/include

extra-lib-dirs:
- /usr/local/opt/icu4c/lib
