resolver: lts-19.3

extra-include-dirs: 
- /usr/local/Cellar/icu4c/71.1/include
extra-lib-dirs: 
- /usr/local/Cellar/icu4c/71.1/lib

packages:
  - "."
allow-newer: true
extra-deps:
- roman-numerals-0.5.1.5
- citeproc-hs-0.3.10@sha256:770a1c3c4be2a1916b7eb994ab038d594d9ddcb83c08a432f655c92a29e611a4,5734

- git: git@github.com:konn/latex-crossref.git
  commit: 79c9ac25f2bb1bfcb40f261a0ea4ffaefd295067

- git: git@github.com:konn/sake.git
  commit: 749eea7de99c8d5041c9f795d594d7d293c92b59

# - git: git@github.com:haskell/text-icu.git
#   commit: 1d2b39abe9f32dc3d19d252391c074ccd82de23f

extra-include-dirs:
  - /usr/local/opt/icu4c/include

extra-lib-dirs:
  - /usr/local/opt/icu4c/lib
